Introduced compatibility with Ruby 1.9.2 rc2 (Thanks Simon Haydon). In 1.9.2, Array#flatten expects that obj.to_ary raise NoMethodError if not defined. Redefinition of Match#method_missing broke this behavior.
Also fixed include paths on tests to compensate for the lack of "." in
1.9.2's $LOAD_PATH.